import 'package:flutter/material.dart';
import 'package:pull_to_refresh/pull_to_refresh.dart';
import 'package:shimmer/shimmer.dart';
import '../../models/bill.dart';
import '../../models/bill_analytics.dart';
import '../../services/data_service.dart';
import '../../utils/formatters.dart';
import '../../utils/navigation_helper.dart';
import '../../widgets/error_widget.dart';
import '../../widgets/bottom_nav_bar.dart';

class BillsScreen extends StatefulWidget {
  const BillsScreen({super.key});

  @override
  State<BillsScreen> createState() => _BillsScreenState();
}

class _BillsScreenState extends State<BillsScreen> {
  final RefreshController _refreshController = RefreshController(initialRefresh: false);
  List<Bill> _bills = [];
  BillAnalytics? _analytics;
  bool _isLoading = true;
  String? _errorMessage;
  String? _selectedStatus;

  @override
  void initState() {
    super.initState();
    _loadDashboard();
  }

  Future<void> _loadDashboard() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });

    try {
      // Load analytics and bills in parallel
      final results = await Future.wait([
        DataService().getBillAnalyticsSummary(),
        DataService().getBills(status: _selectedStatus, page: 1, limit: 20),
      ]);

      _analytics = results[0] as BillAnalytics;
      final billsResult = results[1] as Map<String, dynamic>;
      
      setState(() {
        // Filter bills to show only unique parent bills
        _bills = _filterUniqueBills(billsResult['bills'] as List<Bill>);
        _isLoading = false;
      });
    } catch (e) {
      setState(() {
        _errorMessage = e.toString();
        _isLoading = false;
      });
    }
  }

  void _onRefresh() async {
    await _loadDashboard();
    _refreshController.refreshCompleted();
  }

  void _filterByStatus(String? status) {
    setState(() {
      _selectedStatus = status;
    });
    _loadDashboard();
  }

  List<Bill> _filterUniqueBills(List<Bill> allBills) {
    // Group bills by parentBillId
    final Map<String?, List<Bill>> groupedBills = {};
    
    for (var bill in allBills) {
      final key = bill.parentBillId ?? bill.id; // Use parentBillId as key, or bill.id for parent bills
      groupedBills.putIfAbsent(key, () => []).add(bill);
    }
    
    // For each group, keep only the parent bill (one without parentBillId or the one with isAutoGenerated = false)
    final List<Bill> uniqueBills = [];
    
    for (var group in groupedBills.values) {
      // Find the parent bill (one that doesn't have parentBillId or isAutoGenerated = false)
      final parentBill = group.firstWhere(
        (bill) => bill.parentBillId == null && (bill.isAutoGenerated == false || bill.isAutoGenerated == null),
        orElse: () => group.first,
      );
      uniqueBills.add(parentBill);
    }
    
    // Sort by due date
    uniqueBills.sort((a, b) => a.dueDate.compareTo(b.dueDate));
    
    return uniqueBills;
  }

  Widget _buildSkeletonBox({
    required double width,
    required double height,
    BorderRadius? borderRadius,
    BoxShape shape = BoxShape.rectangle,
  }) {
    return Shimmer.fromColors(
      baseColor: Colors.grey.shade300,
      highlightColor: Colors.grey.shade100,
      child: Container(
        width: width,
        height: height,
        decoration: BoxDecoration(
          color: shape == BoxShape.circle 
              ? Colors.white.withOpacity(0.3)
              : Colors.grey.shade300,
          borderRadius: borderRadius,
          shape: shape,
        ),
      ),
    );
  }

  Widget _buildSkeletonLoader() {
    return SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: double.infinity,
            decoration: const BoxDecoration(
              color: Color(0xFF10B981),
              borderRadius: BorderRadius.only(
                bottomLeft: Radius.circular(30),
                bottomRight: Radius.circular(30),
              ),
            ),
            padding: const EdgeInsets.only(top: 50, left: 20, right: 20, bottom: 30),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                _buildSkeletonBox(width: 150, height: 28),
                const SizedBox(height: 20),
                Row(
                  children: [
                    Expanded(child: _buildSkeletonStatCard()),
                    const SizedBox(width: 12),
                    Expanded(child: _buildSkeletonStatCard()),
                    const SizedBox(width: 12),
                    Expanded(child: _buildSkeletonStatCard()),
                  ],
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),
          
          // Filter chips skeleton
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
            child: Row(
              children: [
                _buildSkeletonBox(width: 60, height: 32, borderRadius: BorderRadius.circular(8)),
                const SizedBox(width: 8),
                _buildSkeletonBox(width: 70, height: 32, borderRadius: BorderRadius.circular(8)),
                const SizedBox(width: 8),
                _buildSkeletonBox(width: 60, height: 32, borderRadius: BorderRadius.circular(8)),
                const SizedBox(width: 8),
                _buildSkeletonBox(width: 80, height: 32, borderRadius: BorderRadius.circular(8)),
              ],
            ),
          ),
          
          // Bills list skeleton
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
            child: Column(
              children: List.generate(5, (index) => Padding(
                padding: const EdgeInsets.only(bottom: 8),
                child: Card(
                  child: ListTile(
                    leading: _buildSkeletonBox(width: 40, height: 40, borderRadius: BorderRadius.circular(10)),
                    title: _buildSkeletonBox(width: 150, height: 16),
                    subtitle: Padding(
                      padding: const EdgeInsets.only(top: 8),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          const SizedBox(height: 4),
                          _buildSkeletonBox(width: 100, height: 12),
                        ],
                      ),
                    ),
                    trailing: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      crossAxisAlignment: CrossAxisAlignment.end,
                      children: [
                        _buildSkeletonBox(width: 80, height: 16),
                        const SizedBox(height: 4),
                        _buildSkeletonBox(width: 60, height: 20, borderRadius: BorderRadius.circular(12)),
                      ],
                    ),
                  ),
                ),
              )),
            ),
          ),
          const SizedBox(height: 20),
        ],
      ),
    );
  }

  Widget _buildSkeletonStatCard() {
    return Shimmer.fromColors(
      baseColor: Colors.white.withOpacity(0.3),
      highlightColor: Colors.white.withOpacity(0.5),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(16),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Container(
                  width: 36,
                  height: 36,
                  decoration: BoxDecoration(
                    color: Colors.grey.shade300,
                    borderRadius: BorderRadius.circular(10),
                  ),
                ),
                Container(
                  width: 32,
                  height: 20,
                  decoration: BoxDecoration(
                    color: Colors.grey.shade300,
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Container(
              width: 60,
              height: 12,
              decoration: BoxDecoration(
                color: Colors.grey.shade300,
                borderRadius: BorderRadius.circular(4),
              ),
            ),
            const SizedBox(height: 4),
            Container(
              width: 80,
              height: 16,
              decoration: BoxDecoration(
                color: Colors.grey.shade300,
                borderRadius: BorderRadius.circular(4),
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildAnalyticsCard() {
    if (_analytics == null) return const SizedBox.shrink();

    return Container(
      padding: const EdgeInsets.symmetric(vertical: 30, horizontal: 20),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text(
            'Bills Overview',
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          const SizedBox(height: 20),
          Row(
            children: [
              Expanded(
                child: _buildStatCard(
                  'Pending',
                  Formatters.formatCurrency(_analytics!.totalPendingAmount),
                  Icons.pending_outlined,
                  const Color(0xFFFFA726),
                  _analytics!.totalPendingBills,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _buildStatCard(
                  'Overdue',
                  Formatters.formatCurrency(_analytics!.totalOverdueAmount),
                  Icons.error_outline,
                  Colors.red,
                  _analytics!.totalOverdueBills,
                ),
              ),
              const SizedBox(width: 12),
              Expanded(
                child: _buildStatCard(
                  'Paid',
                  Formatters.formatCurrency(_analytics!.totalPaidAmount),
                  Icons.check_circle_outline,
                  const Color(0xFF10B981),
                  _analytics!.totalPaidBills,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildStatCard(String label, String amount, IconData icon, Color color, int count) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: Colors.white,
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Colors.black.withOpacity(0.05),
            blurRadius: 10,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Container(
                padding: const EdgeInsets.all(8),
                decoration: BoxDecoration(
                  color: color.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Icon(icon, color: color, size: 20),
              ),
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                decoration: BoxDecoration(
                  color: color.withOpacity(0.1),
                  borderRadius: BorderRadius.circular(12),
                ),
                child: Text(
                  count.toString(),
                  style: TextStyle(
                    fontSize: 12,
                    fontWeight: FontWeight.bold,
                    color: color,
                  ),
                ),
              ),
            ],
          ),
          const SizedBox(height: 12),
          Text(
            label,
            style: const TextStyle(
              fontSize: 12,
              color: Color(0xFF757575),
            ),
          ),
          const SizedBox(height: 4),
          Text(
            amount,
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: color,
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFE8F5E9),
      body: _isLoading && _bills.isEmpty
          ? _buildSkeletonLoader()
          : _errorMessage != null && _bills.isEmpty
              ? ErrorDisplay(
                  message: _errorMessage!,
                  onRetry: _loadDashboard,
                )
              : SmartRefresher(
                  controller: _refreshController,
                  onRefresh: _onRefresh,
                  child: CustomScrollView(
                    slivers: [
                      // Header with Analytics
                      SliverToBoxAdapter(
                        child: Container(
                          width: double.infinity,
                          decoration: const BoxDecoration(
                            color: Color(0xFF10B981),
                            borderRadius: BorderRadius.only(
                              bottomLeft: Radius.circular(30),
                              bottomRight: Radius.circular(30),
                            ),
                          ),
                          child: _buildAnalyticsCard(),
                        ),
                      ),
                      
                      // Filter Chips
                      SliverToBoxAdapter(
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
                          child: Row(
                            children: [
                              FilterChip(
                                label: const Text('All'),
                                selected: _selectedStatus == null,
                                onSelected: (_) => _filterByStatus(null),
                              ),
                              const SizedBox(width: 8),
                              FilterChip(
                                label: const Text('Pending'),
                                selected: _selectedStatus == 'PENDING',
                                onSelected: (_) => _filterByStatus('PENDING'),
                              ),
                              const SizedBox(width: 8),
                              FilterChip(
                                label: const Text('Paid'),
                                selected: _selectedStatus == 'PAID',
                                onSelected: (_) => _filterByStatus('PAID'),
                              ),
                              const SizedBox(width: 8),
                              FilterChip(
                                label: const Text('Overdue'),
                                selected: _selectedStatus == 'OVERDUE',
                                onSelected: (_) => _filterByStatus('OVERDUE'),
                              ),
                            ],
                          ),
                        ),
                      ),

                      // Bills List
                      _bills.isEmpty
                          ? SliverFillRemaining(
                              child: Center(
                                child: Column(
                                  mainAxisAlignment: MainAxisAlignment.center,
                                  children: [
                                    Icon(
                                      Icons.receipt_long_outlined,
                                      size: 64,
                                      color: Colors.grey.shade400,
                                    ),
                                    const SizedBox(height: 16),
                                    Text(
                                      'No bills found',
                                      style: TextStyle(
                                        fontSize: 16,
                                        color: Colors.grey.shade600,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            )
                          : SliverList(
                              delegate: SliverChildBuilderDelegate(
                                (context, index) {
                                  final bill = _bills[index];
                                  return Card(
                                    margin: const EdgeInsets.symmetric(
                                      horizontal: 16,
                                      vertical: 4,
                                    ),
                                    color: bill.isOverdue
                                        ? Colors.red.shade50
                                        : null,
                                    child: ListTile(
                                      leading: Container(
                                        width: 40,
                                        height: 40,
                                        decoration: BoxDecoration(
                                          color: bill.isOverdue
                                              ? Colors.red.withOpacity(0.1)
                                              : bill.isPaid
                                                  ? const Color(0xFF10B981).withOpacity(0.1)
                                                  : const Color(0xFFFFA726).withOpacity(0.1),
                                          borderRadius: BorderRadius.circular(10),
                                        ),
                                        child: Icon(
                                          Icons.receipt_long,
                                          color: bill.isOverdue
                                              ? Colors.red
                                              : bill.isPaid
                                                  ? const Color(0xFF10B981)
                                                  : const Color(0xFFFFA726),
                                          size: 24,
                                        ),
                                      ),
                                      title: Text(
                                        bill.billName,
                                        style: const TextStyle(
                                          fontWeight: FontWeight.bold,
                                        ),
                                      ),
                                      subtitle: Column(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          if (bill.provider != null)
                                            Text(
                                              bill.provider!,
                                              style: const TextStyle(fontSize: 12),
                                            ),
                                          const SizedBox(height: 4),
                                          Text(
                                            'Due: ${Formatters.formatDate(bill.dueDate)}',
                                            style: TextStyle(
                                              color: bill.isOverdue ? Colors.red : null,
                                              fontWeight: bill.isOverdue
                                                  ? FontWeight.bold
                                                  : null,
                                              fontSize: 12,
                                            ),
                                          ),
                                        ],
                                      ),
                                      trailing: Column(
                                        mainAxisAlignment: MainAxisAlignment.center,
                                        crossAxisAlignment: CrossAxisAlignment.end,
                                        children: [
                                          Text(
                                            Formatters.formatCurrency(bill.amount),
                                            style: const TextStyle(
                                              fontWeight: FontWeight.bold,
                                              fontSize: 16,
                                            ),
                                          ),
                                          const SizedBox(height: 4),
                                          Container(
                                            padding: const EdgeInsets.symmetric(
                                              horizontal: 8,
                                              vertical: 2,
                                            ),
                                            decoration: BoxDecoration(
                                              color: bill.isOverdue
                                                  ? Colors.red
                                                  : bill.isPaid
                                                      ? const Color(0xFF10B981)
                                                      : const Color(0xFFFFA726),
                                              borderRadius: BorderRadius.circular(12),
                                            ),
                                            child: Text(
                                              bill.status,
                                              style: const TextStyle(
                                                color: Colors.white,
                                                fontSize: 10,
                                              ),
                                            ),
                                          ),
                                        ],
                                      ),
                                      onTap: () {
                                        NavigationHelper.navigateTo(
                                          context,
                                          'bill-detail',
                                          params: {'id': bill.id},
                                        );
                                      },
                                    ),
                                  );
                                },
                                childCount: _bills.length,
                              ),
                            ),

                      // Bottom spacing
                      SliverToBoxAdapter(
                        child: const SizedBox(height: 20),
                      ),
                    ],
                  ),
                ),
      bottomNavigationBar: const BottomNavBar(currentIndex: 2),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          // TODO: Navigate to add bill screen
          NavigationHelper.showSnackBar(
            context,
            'Add Bill feature coming soon',
            backgroundColor: const Color(0xFF2196F3),
          );
        },
        backgroundColor: const Color(0xFF10B981),
        child: const Icon(Icons.add, color: Colors.white),
      ),
    );
  }

  @override
  void dispose() {
    _refreshController.dispose();
    super.dispose();
  }
}
