import 'package:equatable/equatable.dart';
import '../utils/json_parser.dart';

class Bill extends Equatable {
  final String id;
  final String billName;
  final double amount;
  final DateTime dueDate;
  final String status; // 'PENDING', 'PAID', 'OVERDUE'
  final String? provider;
  final String? billType; // 'utility', 'subscription', 'loan', 'others'
  final String? frequency; // 'monthly', 'quarterly', 'yearly'
  final String? notes;
  final String? referenceNumber;
  final String? userId;
  final DateTime? createdAt;
  final DateTime? updatedAt;
  final DateTime? paidAt;
  final bool? isAutoGenerated;
  final bool? autoGenerateNext;
  final DateTime? confirmedAt;
  final String? parentBillId;

  const Bill({
    required this.id,
    required this.billName,
    required this.amount,
    required this.dueDate,
    required this.status,
    this.provider,
    this.billType,
    this.frequency,
    this.notes,
    this.referenceNumber,
    this.userId,
    this.createdAt,
    this.updatedAt,
    this.paidAt,
    this.isAutoGenerated,
    this.autoGenerateNext,
    this.confirmedAt,
    this.parentBillId,
  });

  factory Bill.fromJson(Map<String, dynamic> json) {
    return Bill(
      id: json['id'] as String,
      billName: json['billName'] as String,
      amount: JsonParser.parseDoubleRequired(json['amount']),
      dueDate: DateTime.parse(json['dueDate'] as String),
      status: json['status'] as String,
      provider: json['provider'] as String?,
      billType: json['billType'] as String?,
      frequency: json['frequency'] as String?,
      notes: json['notes'] as String?,
      referenceNumber: json['referenceNumber'] as String?,
      userId: json['userId'] as String?,
      createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt'] as String) : null,
      updatedAt: json['updatedAt'] != null ? DateTime.parse(json['updatedAt'] as String) : null,
      paidAt: json['paidAt'] != null ? DateTime.parse(json['paidAt'] as String) : null,
      isAutoGenerated: json['isAutoGenerated'] as bool?,
      autoGenerateNext: json['autoGenerateNext'] as bool?,
      confirmedAt: json['confirmedAt'] != null ? DateTime.parse(json['confirmedAt'] as String) : null,
      parentBillId: json['parentBillId'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'billName': billName,
      'amount': amount,
      'dueDate': dueDate.toIso8601String(),
      'status': status,
      'provider': provider,
      'billType': billType,
      'frequency': frequency,
      'notes': notes,
      'referenceNumber': referenceNumber,
      'userId': userId,
      'createdAt': createdAt?.toIso8601String(),
      'updatedAt': updatedAt?.toIso8601String(),
      'paidAt': paidAt?.toIso8601String(),
      'isAutoGenerated': isAutoGenerated,
      'autoGenerateNext': autoGenerateNext,
      'confirmedAt': confirmedAt?.toIso8601String(),
      'parentBillId': parentBillId,
    };
  }

  bool get isOverdue => status == 'OVERDUE' || 
      (status == 'PENDING' && dueDate.isBefore(DateTime.now()));
  bool get isPending => status == 'PENDING' && !isOverdue;
  bool get isPaid => status == 'PAID';

  @override
  List<Object?> get props => [
        id,
        billName,
        amount,
        dueDate,
        status,
        provider,
        billType,
        frequency,
        notes,
        referenceNumber,
        userId,
        createdAt,
        updatedAt,
        paidAt,
        isAutoGenerated,
        autoGenerateNext,
        confirmedAt,
        parentBillId,
      ];
}

