import 'package:equatable/equatable.dart';
import '../utils/json_parser.dart';

class Utility extends Equatable {
  final String id;
  final String userId;
  final String utilityName;
  final String utilityType;
  final String provider;
  final String? accountNumber;
  final String? unit;
  final double? consumption;
  final double? costPerUnit;
  final double amount;
  final DateTime billingDate;
  final DateTime dueDate;
  final String status;
  final String? notes;
  final String? referenceNumber;
  final double? previousReading;
  final double? currentReading;
  final DateTime? readingDate;
  final String? propertyAddress;
  final String? meterNumber;
  final bool autoGenerateNext;
  final bool isAutoGenerated;
  final DateTime? confirmedAt;
  final String? parentUtilityId;
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? paidAt;

  const Utility({
    required this.id,
    required this.userId,
    required this.utilityName,
    required this.utilityType,
    required this.provider,
    this.accountNumber,
    this.unit,
    this.consumption,
    this.costPerUnit,
    required this.amount,
    required this.billingDate,
    required this.dueDate,
    required this.status,
    this.notes,
    this.referenceNumber,
    this.previousReading,
    this.currentReading,
    this.readingDate,
    this.propertyAddress,
    this.meterNumber,
    required this.autoGenerateNext,
    required this.isAutoGenerated,
    this.confirmedAt,
    this.parentUtilityId,
    required this.createdAt,
    required this.updatedAt,
    this.paidAt,
  });

  factory Utility.fromJson(Map<String, dynamic> json) {
    return Utility(
      id: json['id'] as String,
      userId: json['userId'] as String,
      utilityName: json['utilityName'] as String,
      utilityType: json['utilityType'] as String,
      provider: json['provider'] as String,
      accountNumber: json['accountNumber'] as String?,
      unit: json['unit'] as String?,
      consumption: JsonParser.parseDouble(json['consumption']),
      costPerUnit: JsonParser.parseDouble(json['costPerUnit']),
      amount: JsonParser.parseDoubleRequired(json['amount']),
      billingDate: DateTime.parse(json['billingDate'] as String),
      dueDate: DateTime.parse(json['dueDate'] as String),
      status: json['status'] as String,
      notes: json['notes'] as String?,
      referenceNumber: json['referenceNumber'] as String?,
      previousReading: JsonParser.parseDouble(json['previousReading']),
      currentReading: JsonParser.parseDouble(json['currentReading']),
      readingDate: json['readingDate'] != null
          ? DateTime.parse(json['readingDate'] as String)
          : null,
      propertyAddress: json['propertyAddress'] as String?,
      meterNumber: json['meterNumber'] as String?,
      autoGenerateNext: json['autoGenerateNext'] as bool? ?? false,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      confirmedAt: json['confirmedAt'] != null
          ? DateTime.parse(json['confirmedAt'] as String)
          : null,
      parentUtilityId: json['parentUtilityId'] as String?,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      paidAt: json['paidAt'] != null
          ? DateTime.parse(json['paidAt'] as String)
          : null,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'userId': userId,
      'utilityName': utilityName,
      'utilityType': utilityType,
      'provider': provider,
      'accountNumber': accountNumber,
      'unit': unit,
      'consumption': consumption,
      'costPerUnit': costPerUnit,
      'amount': amount,
      'billingDate': billingDate.toIso8601String(),
      'dueDate': dueDate.toIso8601String(),
      'status': status,
      'notes': notes,
      'referenceNumber': referenceNumber,
      'previousReading': previousReading,
      'currentReading': currentReading,
      'readingDate': readingDate?.toIso8601String(),
      'propertyAddress': propertyAddress,
      'meterNumber': meterNumber,
      'autoGenerateNext': autoGenerateNext,
      'isAutoGenerated': isAutoGenerated,
      'confirmedAt': confirmedAt?.toIso8601String(),
      'parentUtilityId': parentUtilityId,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'paidAt': paidAt?.toIso8601String(),
    };
  }

  bool get isOverdue =>
      status == 'OVERDUE' ||
      (status == 'PENDING' && dueDate.isBefore(DateTime.now()));
  bool get isPending => status == 'PENDING' && !isOverdue;
  bool get isPaid => status == 'PAID';

  @override
  List<Object?> get props => [
        id,
        userId,
        utilityName,
        utilityType,
        provider,
        accountNumber,
        unit,
        consumption,
        costPerUnit,
        amount,
        billingDate,
        dueDate,
        status,
        notes,
        referenceNumber,
        previousReading,
        currentReading,
        readingDate,
        propertyAddress,
        meterNumber,
        autoGenerateNext,
        isAutoGenerated,
        confirmedAt,
        parentUtilityId,
        createdAt,
        updatedAt,
        paidAt,
      ];
}

